import {
  addDoc,
  arrayUnion,
  collection,
  deleteDoc,
  doc,
  getDocs,
  limit,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  setDoc,
  updateDoc,
  where,
} from 'firebase/firestore';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { db } from '../config/firebase';
import { buildPreview, notifyOthers } from './notifications';
import type { Chat, Message } from '../types';

/** The family group where everyone is present. */
export const FAMILY_CHAT_ID = 'family';

/**
 * The ID of the chat between two people is generated by sorting their UIDs.
 * This way both parties reach the same chat.
 */
export function directChatId(uid1: string, uid2: string) {
  return `direct_${[uid1, uid2].sort().join('_')}`;
}

/** Live tracks the chats the user is a member of. */
export function subscribeToChats(uid: string, onChange: (chats: Chat[]) => void) {
  const q = query(collection(db, 'chats'), where('members', 'array-contains', uid));

  return onSnapshot(
    q,
    (snapshot) => {
      const chats = snapshot.docs.map((d) => ({ id: d.id, ...d.data() }) as Chat);
      // Let the most recently talked be at the top; if no messages, bring the group forward.
      chats.sort((a, b) => {
        const timeA = a.updatedAt?.toMillis?.() ?? 0;
        const timeB = b.updatedAt?.toMillis?.() ?? 0;
        if (timeA !== timeB) return timeB - timeA;
        return a.type === 'group' ? -1 : 1;
      });
      onChange(chats);
    },
    (error) => console.warn('[chat] chats could not be tracked', error)
  );
}

/** If a direct chat does not exist, creates it and returns its ID. */
export async function ensureDirectChat(me: string, other: string) {
  const chatId = directChatId(me, other);
  await setDoc(
    doc(db, 'chats', chatId),
    { type: 'direct', name: '', members: [me, other].sort() },
    { merge: true }
  );
  return chatId;
}

/**
 * Records the last time the user cleared this chat.
 * Messages are not deleted from the other party; they are just not shown to this user.
 */
export async function clearChatForMe(chatId: string, uid: string) {
  try {
    await AsyncStorage.setItem(`cleared_${chatId}_${uid}`, String(Date.now()));
  } catch (err) {
    console.warn('[chat] could not cache clearedAt locally', err);
  }
  await setDoc(doc(db, 'chats', chatId, 'state', uid), { clearedAt: serverTimestamp() });
}

/** Tracks the user's clear time in this chat. */
export function subscribeToChatState(
  chatId: string,
  uid: string,
  onChange: (clearedAt: number | null) => void
) {
  return onSnapshot(
    doc(db, 'chats', chatId, 'state', uid),
    (snapshot) => onChange(snapshot.data()?.clearedAt?.toMillis?.() ?? null),
    () => onChange(null)
  );
}

/**
 * Un-sends the sent message and updates the chat's last message summary.
 * Security rules only allow deletion if the other party HAS NOT READ IT YET.
 */
export async function unsendMessage(chatId: string, messageId: string) {
  await deleteDoc(doc(db, 'chats', chatId, 'messages', messageId));

  // Update chat summary with the newest remaining message so chat list doesn't show deleted message
  try {
    const remainingQuery = query(
      messagesRef(chatId),
      orderBy('createdAt', 'desc'),
      limit(1)
    );
    const remainingSnap = await getDocs(remainingQuery);
    if (!remainingSnap.empty) {
      const latest = remainingSnap.docs[0].data() as Message;
      const previewText =
        latest.type === 'text'
          ? latest.text
          : latest.type === 'video'
            ? 'Video'
            : latest.type === 'file'
              ? latest.fileName || 'Document'
              : 'Photo';
      await updateDoc(doc(db, 'chats', chatId), {
        lastMessage: {
          text: previewText,
          senderName: latest.senderName,
          at: latest.createdAt,
        },
        updatedAt: latest.createdAt ?? serverTimestamp(),
      });
    } else {
      await updateDoc(doc(db, 'chats', chatId), {
        lastMessage: null,
        updatedAt: serverTimestamp(),
      });
    }
  } catch (err) {
    console.warn('[chat] could not update last message on unsend', err);
  }
}

/** The maximum number of messages fetched at a time. */
const MESSAGE_PAGE_SIZE = 100;

function messagesRef(chatId: string) {
  return collection(db, 'chats', chatId, 'messages');
}

/**
 * Live listens to messages in the chat.
 * The newest ones come from Firestore, displayed in a reverse list on the screen.
 */
export function subscribeToMessages(
  chatId: string,
  onChange: (messages: Message[]) => void,
  onError?: (error: Error) => void
) {
  const messagesQuery = query(
    messagesRef(chatId),
    orderBy('createdAt', 'desc'),
    limit(MESSAGE_PAGE_SIZE)
  );

  return onSnapshot(
    messagesQuery,
    (snapshot) => {
      const messages = snapshot.docs.map((docSnapshot) => ({
        id: docSnapshot.id,
        ...docSnapshot.data(),
      })) as Message[];
      onChange(messages);
    },
    (error) => {
      console.warn('[chat] messages could not be tracked', error);
      onError?.(error);
    }
  );
}

/** Sends a text message to the chat and updates the chat summary. */
export async function sendTextMessage(
  chatId: string,
  sender: { uid: string; name: string },
  text: string
) {
  const trimmed = text.trim();
  if (!trimmed) return;

  await addDoc(messagesRef(chatId), {
    senderId: sender.uid,
    senderName: sender.name,
    type: 'text',
    text: trimmed,
    mediaUrl: null,
    createdAt: serverTimestamp(),
    readBy: [sender.uid],
  });

  // Summary field to show the last message in the chat list.
  await setDoc(
    doc(db, 'chats', chatId),
    {
      lastMessage: { text: trimmed, senderName: sender.name, at: serverTimestamp() },
      updatedAt: serverTimestamp(),
    },
    { merge: true }
  );

  await notifyOthers(chatId, sender, buildPreview('text', trimmed));
}

/** Sends a photo or video message to the chat. */
export async function sendMediaMessage(
  chatId: string,
  sender: { uid: string; name: string },
  media: {
    url: string;
    kind: 'image' | 'video' | 'file';
    thumbUrl?: string | null;
    fileName?: string | null;
    fileSize?: number | null;
  }
) {
  await addDoc(messagesRef(chatId), {
    senderId: sender.uid,
    senderName: sender.name,
    type: media.kind,
    text: '',
    mediaUrl: media.url,
    thumbUrl: media.thumbUrl ?? null,
    fileName: media.fileName ?? null,
    fileSize: media.fileSize ?? null,
    createdAt: serverTimestamp(),
    readBy: [sender.uid],
  });

  // Summary field to show the last message in the chat list.
  await setDoc(
    doc(db, 'chats', chatId),
    {
      lastMessage: {
        text:
          media.kind === 'video'
            ? 'Video'
            : media.kind === 'file'
              ? media.fileName || 'Document'
              : 'Photo',
        senderName: sender.name,
        at: serverTimestamp(),
      },
      updatedAt: serverTimestamp(),
    },
    { merge: true }
  );

  await notifyOthers(chatId, sender, buildPreview(media.kind, ''));
}

/** Marks the messages visible on the screen as read. */
export async function markMessagesAsRead(chatId: string, messageIds: string[], uid: string) {
  await Promise.all(
    messageIds.map((messageId) =>
      updateDoc(doc(db, 'chats', chatId, 'messages', messageId), {
        readBy: arrayUnion(uid),
      }).catch((error) => console.warn('[chat] read receipt could not be written', error))
    )
  );
}
